name: Actions 😎

on:
  push:
    branches:
      - main
    paths: 
      - 'Cat/**'
      - '.github/workflows/main.yml'

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      # Cache
      - uses: actions/cache@v4
        with:
          path: |
            Cat/Assets
            Cat/Packages
            Cat/ProjectSettings
          key: Library-${{ hashFiles('Cat/Assets/**', 'Cat/Packages/**', 'Cat/ProjectSettings/**') }}

      # Test
      # - name: Run tests
      #   uses: game-ci/unity-test-runner@v4
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #   with:
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: Cat
          allowDirtyBuild: true

      # Output
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
